SRC = ft_display_file.c
NAME = ft_display_file
FLAGS = -Wall -Werror -Wextra
$(NAME) : ft_display_file.c
	gcc $(FLAGS) -o $(NAME) $(SRC)
all: $(NAME)
clean: 
	rm -f *.o
fclean: clean 
	rm -f $(NAME)
.PHONY: all clean fclean ft_display_name
